config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'welcome#index'
  	resources :formulas
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/formula.rb
class Formula < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 before_action :authenticate_user!
def configure_permitted_parameters
  devise_parameter_sanitizer.permit(:sign_up) do |user_params|

  user_params.permit({ roles: [] }, :email, :password, :password_confirmation, :name)

  end



  devise_parameter_sanitizer.permit(:account_update) do |user_params|

  user_params.permit({ roles: [] }, :email, :password, :password_confirmation, :current_password, :name)

  end
  end

end

app/controllers/formulas_controller.rb
class FormulasController < ApplicationController
  before_action :set_formula, only: [:show, :edit, :update, :destroy]

  # GET /formulas
  # GET /formulas.json
  def index
    @formulas = Formula.all
  end

  # GET /formulas/1
  # GET /formulas/1.json
  def show
  end

  # GET /formulas/new
  def new
    @formula = Formula.new
  end

  # GET /formulas/1/edit
  def edit
  end

  # POST /formulas
  # POST /formulas.json
  def create
    @formula = Formula.new(formula_params)

    respond_to do |format|
      if @formula.save
        format.html { redirect_to @formula, notice: 'Formula was successfully created.' }
        format.json { render :show, status: :created, location: @formula }
      else
        format.html { render :new }
        format.json { render json: @formula.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /formulas/1
  # PATCH/PUT /formulas/1.json
  def update
    respond_to do |format|
      if @formula.update(formula_params)
        format.html { redirect_to @formula, notice: 'Formula was successfully updated.' }
        format.json { render :show, status: :ok, location: @formula }
      else
        format.html { render :edit }
        format.json { render json: @formula.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /formulas/1
  # DELETE /formulas/1.json
  def destroy
    @formula.destroy
    respond_to do |format|
      format.html { redirect_to formulas_url, notice: 'Formula was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_formula
      @formula = Formula.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def formula_params
      params.require(:formula).permit(:name, :title, :description, :kill, :kd, :hd)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/formulas_helper.rb
module FormulasHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/formulas/_form.html.erb
<%= form_with(model: formula, local: true) do |form| %>
  <% if formula.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(formula.errors.count, "error") %> prohibited this formula from being saved:</h2>

      <ul>
        <% formula.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class="title">
  <h1>New Formula</h1>
  <div class="field">
    <h2><%= form.label :name %></h2>
    <%= form.text_field :name,class: "form-control" %>
  </div>

  <div class="field">
   <h2> <%= form.label :title %></h2>
   <%= form.text_field :title,class: "form-control" %>
  </div>

  <div class="field">
    <h2><%= form.label :description %></h2>
    <%= form.text_field :description,class: "form-control" %>
  </div>

  <div class="action">
  <%= form.submit "Update",class:"btfhn" %> 
  </div>       


  <%= link_to 'Back', formulas_path %>
  </div>
<% end %>
<style type="text/css">
  .btfhn{
    margin-top: 10px;
    border: 1px solid #fff;
    padding: 10px 20px;
    color: #fff;
    text-decoration: none;
    transition: 1s ease;
    background-color: transparent;
  }
   .btfhn:hover{
    background-color: #fff;
    color: #000;
    cursor: 
   }
   .form-control{
    background-color: transparent;
   }
   .form-control:hover{
     background-color: #fff;
    color: #000;
     -webkit-transition: width .35s ease-in-out;
  transition: width .35s ease-in-out;
   }
  
</style>

app/views/formulas/edit.html.erb
<%= render 'form', formula: @formula %>

app/views/formulas/index.html.erb
<div class="title">
<h1>Player Profile</h1>
<table>
<div class="card">
  <thead>
    <tr>
      <th><h2>Name</h2></th>
      <th><h2>Matches</h2></th>
      <th><h2>Tier</h2></th>
      <th><h2>Kill</h2></th>
      <th><h2>K/D</h2></th>
      <th><h2>Headshot</h2></th>
      <th colspan="6"></th>
    </tr>
  </thead>

  <tbody>
    <% @formulas.each do |formula| %>
      <tr>
        <td><h3><%= formula.name %></h3></td>
        <td><h3><%= formula.title %></h3></td>
        <td><h3><%= formula.description %></h3></td>
         <td><h3><%= formula.kill %></h3></td>
          <td><h3><%= formula.kd %></h3></td>
           <td><h3><%= formula.hd %></h3></td>
        <td><%= link_to 'Show', formula,class: "new" %></td>
        <td><%= link_to 'Edit', edit_formula_path(formula),class: "new" %></td>
        <td><%= link_to 'Destroy', formula, method: :delete, data: { confirm: 'Are you sure?' },class: "new" %></td>
      </tr>
    <% end %>
  </tbody>
</div>
</table>
<br>

<%= link_to 'New Formula', new_formula_path,class: "btn" %>
</div>
<style type="text/css">
  .new{
    margin-top: 10px;
    border: 1px solid #fff;
    padding: 2px 5px;
    color: #fff;
    text-decoration: none;
    transition: 1s ease;
    background-color: transparent;
  }
   .new:hover{
    background-color: #fff;
    color: #000;
    text-decoration: none;
   }
   .card{
    background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.5));
   }
</style>

app/views/formulas/new.html.erb
<%= render 'form', formula: @formula %>

<%#= link_to 'Back', formulas_path %>
</div>

app/views/formulas/show.html.erb
<p id="notice"><%= notice %></p>
<div class="title">
  <h4>Name:<h4>
 <h2><%= @formula.name %></h2> 
<br>
 <h4>Title:</h4><h2>
  <%= @formula.title %></h2> 
<br>
<h4>Description:</h4>
<h2><%= @formula.description %></h2>
<br>
<h4>Kill:</h4>
<h2><%= @formula.kill %></h2>
<br>
<h4>K/D:</h4>
<h2><%= @formula.kd %></h2>
<br>
<h4>Headshot:</h4>
<h2><%= @formula.hd %></h2>


<%= link_to 'Edit', edit_formula_path(@formula) %> |
<%= link_to 'Back', formulas_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebDesign</title>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
  </head>

  <body>
    <div class="container">
    <header>
      <div class="main">
        <div class="logo">
          <img src="http://www.pngmart.com/files/10/PUBG-Logo-PNG-File.png">
        </div>
        <ul>
          <li class="active"><a href="#">Home</a></li>
          <li><a href="/formulas">Clan</a></li>
          <li><a href="#">Contacts</a></li>
          <li><a href="#">Gallery</a></li>
          <li><a href="#">About</a></li>
          <% if current_user %>
            <div class="btn-group">
                    <a id="dLabel" role="button" data-toggle="dropdown" class="btn btn-primary dropdown-toggle"
                       href="">
                        <%= current_user.name %>
                    </a>
                    <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu">
                      <li><a class="dropdown-item" href="users/edit">Edit Profile</a></li>
                      <li><a class="dropdown-item" href="users/sign_out">Log Out</a></li>
                      <li class="dropdown-divider"></li>
                    </ul>
                </div>
          <% end %>
        </ul>
      </div>
                           
    </header>   
  </div>
  <% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-d
anger"><%= alert %></p>
<% end %>
   <%= yield %>
  </body>
</html>
<style type="text/css">
   @charset "UTF-8";
  /* CSS Document */
@import url('https://fonts.googleapis.com/css?family=Century+Gothic');


  *{
    margin: 0;
    padding: 0;
    font-family: Century Gothic;
    font-size: 20px;
  }
  .dropdown-submenu {
      position: relative;
  }

  .dropdown-submenu> a:after {
      content: ">";
      float: right;
  }

  .dropdown-submenu>.dropdown-menu {
      top: 0;
      left: 100%;
      margin-top: 0px;
      margin-left: 0px;
  }

  .dropdown-submenu:hover>.dropdown-menu {
      display: block;
  }
 
  body{
     background-image: linear-gradient(rgba(0,0,0,0.5),rgba(0,0,0,0.5)), url("https://images.wallpaperscraft.com/image/maldives_tropical_beach_island_86184_3840x2400.jpg");

    height: 100vh;
    background-size: cover;
    background-position: center;
  }
  ul{
    float: right;
    list-style-type: none;
    margin-top: 25px;
  }
  ul li{
    display: inline-block;
  }
  ul li a{
    text-decoration: none;
    color: #fff;
    padding: 10px;
    border: 1px solid transparent;
    transition: 0.6s ease;
  }
  ul li.active a{
     background-color: #fff;
    color: #000;
  }
   ul li a:hover{
    background-color: #fff;
    color: #000;
    text-decoration: none;
   }
   .logo img{
        float: left;
        width: 200px;
        height: auto;
   }
   .main{
    max-width: 1200px;
   }
   .title{
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%,-50%);
   }
   .title h1{
    color: #fff;
    font-size: 70px;
   }
   .title h2{
    color: #fff;
    font-size: 20px;
   }
   .title h3{
       color: #fff;
    font-size: 15px;
   }
    .title h4{
    color: #fff;
    font-size: 40px;
    margin: 10px;
   }
   .button{
    position: absolute;
    top: 60%;
    left: 50%;
    transform: translate(-50%,-50%);
   }
   .btn{
    border: 1px solid #fff;
    padding: 10px 30px;
    color: #fff;
    text-decoration: none;
    transition: 1s ease;
   }
   .btn:hover{
     background-color: #fff;
    color: #000;
   }

   tbody{
     padding: 10px;
   }
</style>
<script type="text/javascript">
  $(".btn-group, .dropdown").hover(
  function () {
      $('>.dropdown-menu', this).stop(true, true).fadeIn("fast");
      $(this).addClass('open');
  },
  function () {
      $('>.dropdown-menu', this).stop(true, true).fadeOut("fast");
      $(this).removeClass('open');
  });
</script>

app/views/welcome/index.html.erb
 <div class="title">
        <h1>PUBG MOBILE</h1>
      </div>
      <div class="button">
        <a href="#" class="btn">WATCH MATCHES</a>
        <a href="#" class="btn">ROYAL PASS</a>
      </div>   